name: test
on:
  pull_request:
    paths:
      - "**.py"
  workflow_dispatch:

run-name: test

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up mise
        uses: jdx/mise-action@v2
      - name: Install dependencies
        run: uv sync --dev --all-extras --locked
      - name: Run tests
        run: uv run pytest -s
